### ISSUE TITLE
Add ability to cite?

### ISSUE THREAD

**Issue by AlecThomson** [CIRADA-Tools/RMTable#2]
Hey @Cameron-Van-Eck ,

It'd be great to be able to cite both this format and the master catalogue. Would it be possible to add this repo to https://zenodo.org/, or some similar service, to generate a citable DOI?

Thanks!

**Comment by Cameron-Van-Eck** [comment]
Hey Alec!

What kind of timescale do you anticipate for needing to cite the master catalog/format? I'm planning on making a big push on this in the next couple of weeks, so if it's not super urgent then I can do that once I've gotten to the other side of that work (since things will probably change a bit in the mean time).

I was planning on using Zenodo to host the catalog, since it's pushing the limits of what Github will accept for file sizes.

Cheers,
Cameron

**Comment by AlecThomson** [comment]
Hey Cameron,

That sounds great! And that timeline is totally fine for me as well. Thanks!

**Comment by AlecThomson** [comment]
Closing since the catalogue is now on https://zenodo.org/record/6702843
